name: Build DCNv4 Windows Wheel

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2019 

    strategy:
      matrix:

        python-version: ['3.10'] 

        cuda-version: ['12.1.0'] 
    
        pytorch-version: ['2.4.0']
     
        pytorch-index: ['cu121'] 

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    
    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.19
      id: cuda-toolkit
      with:
        cuda: ${{ matrix.cuda-version }}
        method: 'network' 
        sub-packages: '["nvcc", "visual_studio_integration"]' 

  
    - name: Install PyTorch and Ninja
      shell: cmd
      run: |
        python -m pip install --upgrade pip
      
        pip install torch==${{ matrix.pytorch-version }} --index-url https://download.pytorch.org/whl/${{ matrix.pytorch-index }}
       
        pip install ninja setuptools wheel

    - name: Build Wheel
      shell: cmd
      env:
       
        TORCH_CUDA_ARCH_LIST: "8.6;8.9" 
        DISTUTILS_USE_SDK: 1
        MSSdk: 1
      
      run: |

        cd DCNv4_op
        
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        
       
        nvcc --version
        
       
        python setup.py bdist_wheel

        
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        
       
        nvcc --version
        
       
        python setup.py bdist_wheel

    
    - name: List Artifacts
      shell: cmd
      run: dir dist

   
    - name: Upload Wheel
      uses: actions/upload-artifact@v4
      with:
        name: dcnv4-windows-wheel-${{ matrix.python-version }}-cuda${{ matrix.cuda-version }}
        path: dist/*.whl
